### ISSUE TITLE
Optionally allow recording of shortcuts without modifiers pressed

### ISSUE THREAD

**Issue by NeoDarque** [Clipy/KeyHolder#25]
For some scenarios it would be nice to be able to record a shortcut for a key without the use of a modifier. This could be allowed by passing another parameter to the initializer which is then checked in the "validateModifiers" extension function, replacing
return KeyTransformer.carbonFlags(from: modifiers) != 0
...with...
return KeyTransformer.carbonFlags(from: modifiers) != 0 || isEmptyModiersAllowed

I can supply a pull-request if you think this is worthwhile.

**Comment by zenangst** [comment]
I second this proposal, I need it for a new application that I'm building now.
If you accept pull requests I'd be glad to make a PR to fix this up and we can discuss the detail in-depth?

**Comment by zenangst** [comment]
I made a PR for this yesterday #30

**Comment by Econa77** [comment]
Must have a modifiers to add to the macOS shortcut.
Therefore, validating modifiers is not the purpose of this library, which provides a UI for registering OS shortcuts.
