### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by vanshg** [Clipy/KeyHolder#34]
I would like to migrate my project to SPM, and this is the one project that has not yet added support for Swift Package Manager. Would be great if support for this could be added.

**Comment by Econa77** [comment]
@vanshg SPM was difficult to support because it does not yet support the resource, but now it can because it replaces the image resource in #40, and SPM support was added in #41 .
The official release will be v4.0.0, so please wait for a little more development 👍

**Comment by vanshg** [comment]
Sounds good, thank you @Econa77!
