### ISSUE TITLE
Trying to build KeyHolder - isMousePoint is flagged as error.

### ISSUE THREAD

**Issue by jasonm23** [Clipy/KeyHolder#35]
XCode reports that `isMousePoint` is now `mouse`

**Comment by Econa77** [comment]
@jasonm23 The build is successful in my environment and on [CI](https://github.com/Clipy/KeyHolder/actions).
Can you tell me what version of macOS and Xcode you are trying to run?

**Comment by jasonm23** [comment]
I'll update everything and check again

**Comment by jasonm23** [comment]
I'm still on Mojave & XCode 10.2.1 

I will upgrade to XCode 11.3.1

**Comment by jasonm23** [comment]
XCode 11.3.1 upgrade solved the issue for me.  Thank you.
