### ISSUE TITLE
Disable YouTube autoplaying 

### ISSUE THREAD

**Issue by craldaz** [Clipy/KeyHolder#64]
Hi, I use YouTube in my Slidepad but every time I open Slidepad YouTube automatically starts playing if I left a Slidepad window on a YouTube video, even if my current Slidepad window isn't YouTube. 

Is there any chance of disabling auto-playing a YouTube video? It seems difficult but it's also pretty annoying so it would be much appreciated!

**Comment by Econa77** [comment]
It seems like the issue is not related to this library. If there are any problems, please reopen.
