### ISSUE TITLE
Carthage fails to build

### ISSUE THREAD

**Issue by vanshg** [Clipy/KeyHolder#7]
When trying to checkout and build using Carthage, I get this error message
```
*** Building scheme "Magnet" in Magnet.xcworkspace
*** Building scheme "KeyHolder" in KeyHolder.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace ProjectName/Carthage/Checkouts/KeyHolder/KeyHolder.xcworkspace -scheme KeyHolder -configuration Release -derivedDataPath ~/Library/Caches/org.carthage.CarthageKit/DerivedData/KeyHolder/v2.0.1 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile.
```

I also tried manually checking out and opening up in Xcode, like it says in the build instructions, but it says it can't find the library Magnet to include in RecordView, even though the Magnet framework is included in the project

**Comment by Econa77** [comment]
@vanshg I could not reproduce this error. Will you write the following environment?

- Carthage version
- Xcode version
- Swift version

`Task failed with exit code 65:` 
This error is a frequent bug in Xcode. Maybe you may be able to build it if you build again, please try it.
